### ISSUE TITLE
Crashes when using broccoli-cli shorthand

### ISSUE THREAD

**Issue by rhendric** [stfsy/broccoli-livereload#6]
broccoli-cli supports `broccoli b` and `broccoli s` as shorthands for `broccoli build` and `broccoli serve`, respectively.

Using broccoli-livereload with these shorthand commands causes the build to crash, because neither `_building` nor `_serving` gets set to `true`.

**Comment by stfsy** [comment]
hi @rhendric thanks for getting in touch! I have never tried these shorthands actually. But i fixed it now  with the new version [1.6.1](https://github.com/stfsy/broccoli-livereload/blob/master/CHANGELOG.md#161-2020-09-16). 🙂

**Comment by rhendric** [comment]
Fast work, thank you!
